export const ITINERARY_LIST_REQUEST = "ITINERARY_LIST_REQUEST";
export const ITINERARY_LIST_SUCCESS = "ITINERARY_LIST_SUCCESS";
export const ITINERARY_LIST_FAIL = "ITINERARY_LIST_FAIL";

export const ITINERARY_DETAIL_REQUEST = 'ITINERARY_DETAIL_REQUEST';
export const ITINERARY_DETAIL_SUCCESS = 'ITINERARY_DETAIL_SUCCESS';
export const ITINERARY_DETAIL_FAIL = 'ITINERARY_DETAIL_FAIL';

export const ITINERARY_FORM_REQUEST = 'ITINERARY_FORM_REQUEST';
export const NEW_ITINERARY_SUCCESS = "NEW_ITINERARY_SUCCESS"; 
export const NEW_ITINERARY_FAIL = "NEW_ITINERARY_FAIL"; 

export const CREATED_ITINERARY_SUCCESS = "CREATED_ITINERARY_SUCCESS";
 
export const GET_CREATED_ITINERARY_SUCCESS = "GET_CREATED_ITINERARY_SUCCESS"; 
export const GET_CREATED_ITINERARY_REQUEST = "GET_CREATED_ITINERARY_REQUEST"; 
export const GET_CREATED_ITINERARY_FAIL = "GET_CREATED_ITINERARY_FAIL"; 

export const ADD_TRANSPORT_SUCCESS = "ADD_TRANSPORT_SUCCESS";
export const ADD_TRANSPORT_FAIL = "ADD_TRANSPORT_FAIL";

export const ADD_ACCOMODATION_SUCCESS = "ADD_ACCOMODATION_SUCCESS";
export const ADD_ACCOMODATION_FAIL = "ADD_ACCOMODATION_FAIL";

export const ADD_DAILY_ITINERARY_SUCCESS = "ADD_DAILY_ITINERARY_SUCCESS";
export const ADD_DAILY_ITINERARY_FAIL = "ADD_DAILY_ITINERARY_FAIL";

export const ITINERARY_WAS_COMPLETED_SUCCESS = 'ITINERARY_WAS_COMPLETED_SUCCESS';
export const ITINERARY_WAS_COMPLETED_FAIL = 'ITINERARY_WAS_COMPLETED_FAIL';

export const RESET_NEW_ITINERARY = 'RESET_NEW_ITINERARY';